spring.application.name=wallet

spring.datasource.url=jdbc:postgresql://localhost:5432/wallet
spring.datasource.username=postgres-user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true
spring.flyway.schemas=public